"""initial schema

Revision ID: c9f82ff758ea
Revises: 
Create Date: 2026-09-14 20:42:49.525411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9f82ff758ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # citext is needed for Seller.email (case-insensitive uniqueness) —
    # autogenerate doesn't detect/emit extension requirements, add by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_event_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('this_event_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum('AMAZON_IN', 'FLIPKART', 'MEESHO', name='marketplace_code'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('settlement_frequency_days', sa.SmallInteger(), nullable=False),
    sa.Column('payout_split_count', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=False),
    sa.Column('trade_name', sa.Text(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('gstin', sa.Text(), nullable=True),
    sa.Column('pan', sa.Text(), nullable=True),
    sa.Column('udyam_registration_number', sa.Text(), nullable=True),
    sa.Column('msme_classification', sa.Enum('MICRO', 'SMALL', 'MEDIUM', 'NONE', name='msme_classification'), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('primary_state', sa.Text(), nullable=True),
    sa.Column('primary_pincode', sa.Text(), nullable=True),
    sa.Column('principal_place_of_business', sa.Text(), nullable=True),
    sa.Column('bank_account_number', sa.Text(), nullable=True),
    sa.Column('bank_ifsc', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fee_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('category_pattern', sa.Text(), nullable=False),
    sa.Column('fee_type', sa.Enum('REFERRAL', 'CLOSING', 'SHIPPING', 'FBA', 'COLLECTION', name='fee_type'), nullable=False),
    sa.Column('computation_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('internal_sku', sa.Text(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.Text(), nullable=True),
    sa.Column('category_primary', sa.Text(), nullable=True),
    sa.Column('category_sub', sa.Text(), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('dimensions_cm_length', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dimensions_cm_width', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dimensions_cm_height', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('mrp_paise', sa.BigInteger(), nullable=False),
    sa.Column('cost_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('gst_rate', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('gst_rate IN (0, 5, 12, 18, 28)', name='ck_products_gst_rate_valid'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_products_seller_internal_sku', 'products', ['seller_id', 'internal_sku'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('seller_marketplace_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id_on_platform', sa.Text(), nullable=False),
    sa.Column('warehouse_pincode', sa.Text(), nullable=True),
    sa.Column('fulfillment_type', sa.Enum('SELF_SHIP', 'FBA', 'FLIPKART_ADVANTAGE', 'MEESHO_SUPPLIER', name='fulfillment_type'), nullable=False),
    sa.Column('activated_on', sa.Date(), server_default=sa.text('current_date'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'marketplace_id', 'merchant_id_on_platform', name='uq_seller_marketplace_account_seller_marketplace_merchant')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_marketplace_account_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_order_id', sa.Text(), nullable=False),
    sa.Column('buyer_pincode', sa.Text(), nullable=True),
    sa.Column('buyer_state', sa.Text(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('order_status', sa.Enum('PLACED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'RTO', name='order_status'), nullable=False),
    sa.Column('payment_type', sa.Enum('PREPAID', 'COD', name='payment_type'), nullable=False),
    sa.Column('total_gross_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_gst_amount_paise', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tcs_deducted_paise', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tds_deducted_paise', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('shipping_zone', sa.Enum('LOCAL', 'REGIONAL', 'NATIONAL', name='shipping_zone'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_marketplace_account_id'], ['seller_marketplace_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_marketplace_account_id', 'marketplace_order_id', name='uq_orders_account_marketplace_order_id')
    )
    op.create_table('settlement_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_marketplace_account_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_gross_sales_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_fees_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_taxes_deducted_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_returns_refunds_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_reimbursements_paise', sa.BigInteger(), nullable=True),
    sa.Column('net_payout_expected_paise', sa.BigInteger(), nullable=True),
    sa.Column('net_payout_bank_credited_paise', sa.BigInteger(), nullable=True),
    sa.Column('discrepancy_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('file_uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_file_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'PARSED', 'RECONCILING', 'RECONCILED', 'FAILED', name='settlement_status'), server_default=sa.text("'UPLOADED'"), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('rejected_row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_rows_detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['seller_marketplace_account_id'], ['seller_marketplace_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_marketplace_account_id', 'source_file_hash', name='uq_settlement_reports_account_file_hash')
    )
    op.create_table('sku_marketplace_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('seller_marketplace_account_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_sku_id', sa.Text(), nullable=False),
    sa.Column('marketplace_category_id', sa.Text(), nullable=True),
    sa.Column('selling_price_current_paise', sa.BigInteger(), nullable=True),
    sa.Column('selling_price_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('stock_available', sa.Integer(), nullable=True),
    sa.Column('listing_status', sa.Enum('ACTIVE', 'INACTIVE', 'SUPPRESSED', name='listing_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_marketplace_account_id'], ['seller_marketplace_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('sku_marketplace_listing_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_before_gst_paise', sa.BigInteger(), nullable=False),
    sa.Column('unit_gst_rate', sa.Integer(), nullable=False),
    sa.Column('unit_gst_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('line_total_paise', sa.BigInteger(), nullable=False),
    sa.Column('discount_applied_paise', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('promotion_code_used', sa.Text(), nullable=True),
    sa.CheckConstraint('unit_gst_rate IN (0, 5, 12, 18, 28)', name='ck_order_line_items_unit_gst_rate_valid'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sku_marketplace_listing_id'], ['sku_marketplace_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('return_marketplace_id', sa.UUID(), nullable=False),
    sa.Column('return_reason', sa.Enum('DAMAGED', 'WRONG_ITEM', 'NOT_AS_DESCRIBED', 'CHANGE_OF_MIND', 'DEFECTIVE', 'RTO_UNDELIVERED', name='return_reason'), nullable=False),
    sa.Column('return_type', sa.Enum('CUSTOMER_RETURN', 'RTO', name='return_type'), nullable=False),
    sa.Column('return_status', sa.Enum('INITIATED', 'IN_TRANSIT', 'RECEIVED', 'INSPECTED', 'REFUNDED', 'REIMBURSED', 'DISPUTED', name='return_status'), server_default=sa.text("'INITIATED'"), nullable=False),
    sa.Column('initiated_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('refund_amount_expected_paise', sa.BigInteger(), nullable=False),
    sa.Column('refund_amount_credited_paise', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('reimbursement_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('inventory_disposition', sa.Enum('RESTOCKED', 'DAMAGED', 'LOST', 'DISPOSED', 'NOT_YET_RETURNED', name='inventory_disposition'), nullable=True),
    sa.Column('claim_status', sa.Enum('NOT_CLAIMED', 'CLAIMED', 'APPROVED', 'REJECTED', name='claim_status'), server_default=sa.text("'NOT_CLAIMED'"), nullable=False),
    sa.Column('claim_window_expires', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['return_marketplace_id'], ['marketplaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_report_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('amount_description', sa.Text(), nullable=False),
    sa.Column('amount_canonical', sa.Enum('REFERRAL_FEE', 'CLOSING_FEE', 'SHIPPING_FEE', 'COLLECTION_FEE', 'FBA_FEE', 'STORAGE_FEE', 'ADVERTISING_FEE', 'PROMOTION_REBATE', 'TCS', 'TDS', 'REFUND', 'REIMBURSEMENT', 'ADJUSTMENT', 'GST_ON_FEE', name='amount_canonical'), nullable=False),
    sa.Column('amount_value_paise', sa.BigInteger(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('raw_line_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_status', sa.Enum('UNMATCHED', 'MATCHED_EXACT', 'MATCHED_FUZZY', 'ADJUSTMENT', name='match_status'), server_default=sa.text("'UNMATCHED'"), nullable=False),
    sa.Column('expected_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('deviation_paise', sa.BigInteger(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['settlement_report_id'], ['settlement_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_line_items')
    op.drop_table('returns')
    op.drop_table('order_line_items')
    op.drop_table('sku_marketplace_listings')
    op.drop_table('settlement_reports')
    op.drop_table('orders')
    op.drop_table('seller_marketplace_accounts')
    op.drop_index('uq_products_seller_internal_sku', table_name='products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('products')
    op.drop_table('fee_schedules')
    op.drop_table('sellers')
    op.drop_table('marketplaces')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
